name: env variable demo

on: 
  push:
    branches:
      - main
env:
  myman: Github

jobs:
  build:
    runs-on: ubuntu-latest
    steps: |
      echo Name is $myman
      echo Second Name is $name
